version: '3'
services:

  react:
    build:
      dockerfile: ./front/Dockerfile
      context: .
    container_name: library-front
    ports:
      - "8000:8000"
    volumes:
      - ./front:/usr/scr/app
    networks:
      - library-networl

  node:
    build:
      dockerfile: ./api/Dockerfile
      context: .
    container_name: library-api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/scr/app
    networks:
      - library-networl
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "library"
    networks:
      - library-networl

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: "1"
    ports:
      - "8080:80"
    networks:
      - library-networl

networks:
  library-networl:


volumes:
  db-data:
